---
# http://docs.aws.amazon.com/codedeploy/latest/userguide/how-to-run-agent-install.html
- name: Install prerequisites for codedeploy agent
  apt: name={{ packages }} state=latest
  vars:
    packages:
      - ruby2.0
      - wget
  when: ansible_os_family == "Debian" and ansible_distribution_version == 14.04

- name: Install prerequisites for codedeploy agent
  apt: name={{ packages }} state=latest
  vars:
    packages:
      - ruby
      - wget
  when: ansible_os_family == "Debian" and ansible_distribution_version != 14.04

- name: Enable repository from amazon-linux-extras packages to install ruby 2.4 in amazon linux 2 distro
  shell: "amazon-linux-extras enable ruby2.4"
  when: ansible_distribution == 'Amazon' and (ansible_distribution_version == "(Karoo)" or ansible_distribution_version == "2")
  changed_when: False

- name: Install from yum when Red Hat based
  yum: name={{ packages }} state=latest lock_timeout=300
  vars:
    packages:
      - ruby
      - wget
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon'

- name: Download installer
  get_url:
    url: "https://aws-codedeploy-{{ ansible_ec2_placement_region }}.s3.amazonaws.com/latest/install"
    dest: /tmp/install-codedeploy-agent
    mode: o+x

- name: Execute installer
  command: /tmp/install-codedeploy-agent auto

- name: Start daemon
  service:
    name: codedeploy-agent
    state: restarted
    enabled: yes
